export const meta = {
  name: 'speculair-mining-weekly',
  description: 'Weekly Mining Lane A debate (the chain map already produced competitors). Director runs separately after mining-input.',
  phases: [{ title: 'Debate', model: 'opus' }],
}
const DIR = 'backend/_opus_debate/mining'
const RES = DIR + '/results'
const SYMS = ["AEM", "AGI", "ERO", "FSM"]               // have a bundled FMP transcript (read local file)
const ONLINE_SYMS = [] // no FMP transcript - agent fetches the latest one online

// -- PHASE 1 - DEBATE: Interrogator -> Architect (bull/bear + Sum-of-Parts) -> web verification -> CRO. --
// No Radar phase: the monthly chain map already produced true competitors. All names run as
// general-purpose agents so EVERY name (FMP + online) can web-verify its operating facts.
function debatePrompt(sym, online) {
  const BRIEF = 'Read ' + DIR + '/chain_map/' + sym + '.json - this name has an assigned chain(s), business_model, physical anchor, value-chain position, commodity_revenue_share and true competitors. Its input bundle carries a resource_metrics block (deterministic cost-curve/torque proxies: ebitda_margin_ttm + cohort band, fcf_torque_10pct, commodity_beta_2y, ndebt_ebitda) and a chain_regime block (per-chain TAILWIND/NEUTRAL/HEADWIND from the regime sidecar). This is a MINING LANE-A debate, not a catalyst debate: judge (1) COST-CURVE POSITION - the metrics are honest PROXIES; web-verify against company-reported AISC / unit-cost guidance where published, and SAY EXPLICITLY when the proxy and the company-reported figure disagree; (2) CONTRACTING and RESERVE LIFE - the contract book vs spot exposure, reserve/resource life with numbers, NAMED offtake counterparties (an MoU is not a contract); for a royalty/streamer read the royalty book instead: paying assets, operator quality, and whether growth needs capex; (3) CAPITAL DISCIPLINE - the sector besetting sin: capex history through the LAST cycle, buyback/dividend behavior at the top; (4) THE REGIME - read MINING_REGIME.md (repo root) if present for this name chain section and apply the cycle read, else rely on chain_regime. A live catalyst is neither a plus nor a requirement (Lane B owns catalysts). TORQUE IS SYMMETRIC: the bear case MUST price the downside torque with the number (the same fcf_torque_10pct cuts both ways on a -10% move), not just assert commodity risk. Gold and silver price action is NOT evidence for a seat: judge the miner, never the metal chart.'
  const step1 = online
    ? '1. Read ' + DIR + '/inputs/' + sym + '.json (fields metrics_str/sector/signal_type/company + chains/business_model/physical_anchor/commodity_revenue_share/chain_regime/resource_metrics/gates; metrics may include a SEGMENT REVENUE block). NO FMP transcript is bundled. FIRST try the paid FMP MCP tools via ToolSearch (keyword search e.g. "FMP earnings transcript", "FMP statements", "FMP news") for ' + sym + ' and its MOST RECENT earnings-call transcript and quarterly numbers; if FMP has nothing for this ticker, THEN use WebSearch + WebFetch to find the latest transcript / quarterly results / earnings release / management commentary / investor presentation (IR site, Tikr, Seeking Alpha, Investing.com, MarketScreener, plus the latest regulatory filing) - do NOT scrape press-release PDFs by shell. If genuinely nothing is findable, say so and reason from the fundamentals - never fabricate quotes or figures.\n'
    : '1. Read ' + DIR + '/inputs/' + sym + '.json (fields metrics_str/sector/signal_type + chains/business_model/physical_anchor/commodity_revenue_share/chain_regime/resource_metrics/gates; metrics may include a SEGMENT REVENUE block) and ' + DIR + '/transcripts/' + sym + '.txt.\n'
  return 'You run the COMPLETE multi-agent debate for ' + sym + ' as Claude Opus 5 - Interrogator, Architect, then CRO/Moderator - allocating REAL capital to a Mining Lane A name (a profitable operator in a physical value chain). Be skeptical and current-facts-driven; this is a sector where promoters live.\n' +
    step1 +
    '1b. LIVE PRICE (MANDATORY, BEFORE any valuation reasoning): if the metrics block does not state a current price, you MUST fetch the live quote via the FMP MCP tools (ToolSearch, keyword "FMP quote") and state the price + currency you are using. NEVER assume or infer where the stock trades - a fabricated price inverts the entire risk/reward. For dual-listed names state WHICH listing/currency your numbers are in.\n' +
    '2. INTERROGATOR: read ' + DIR + '/interrogator_system.txt; produce the full forensic dossier (8 sections + final "CREDIBILITY_SCORE: <1-5> | TRAJECTORY: <...>"); pay special attention to serial-diluter financing patterns, capacity/backlog inflation, and promoter language - the sector kill list. Write it to ' + DIR + '/dossiers/' + sym + '.md.\n' +
    '3. PEER COMPS: read ' + DIR + '/chain_map/' + sym + '.json (this name has assigned chain(s), value_chain_position and true_competitors) as the relative-value lever for the valuation below (skip if the file is absent).\n' +
    '4. ARCHITECT: read ' + DIR + '/architect_system.txt; produce bull_thesis and bear_thesis, AND a SUM-OF-PARTS valuation - value the business by its PARTS (segment SoP from the SEGMENT REVENUE block x peer multiples where present; else whole-company intrinsic via peer multiple / NAV where the asset base supports one), then apply overlays (net cash, announced asset-sales, royalty/streaming or recurring-service portfolios valued separately). The bear case MUST price the DOWNSIDE with NUMBERS, not assertions. Output sop_bull (favorable parts) and sop_bear (adverse parts, ASSUMING THE CHAIN REGIME TURNS AGAINST IT), each a per-share value + the parts breakdown.\n' +
    '5. OPERATING VERIFICATION (web, MANDATORY): identify the load-bearing operating facts for this chain (cost/unit-cost or gross-margin guidance, contracted volumes or backlog and its realized-price mechanics, reserve life or order book, named counterparties and dated milestones) and verify their CURRENT status as of today - FIRST the paid FMP MCP tools via ToolSearch ("FMP statements", "FMP news", "FMP earnings transcript"), then WebSearch/WebFetch for what FMP lacks. Where the deterministic proxy metrics DISAGREE with company-reported figures, say so explicitly. Also emit catalyst_status = FIRED | ARB | PENDING_HARD | SOFT_EXTENDED | UNVERIFIABLE for the record (it must NOT drive the verdict - Lane B owns catalysts). Dated evidence; never fabricate - a price or a contract without a source does not appear.\n' +
    '6. CRO/MODERATOR: read ' + DIR + '/moderator_system.txt; ' + BRIEF + ' RECONCILE sop_bull/sop_bear into a base-case sop_fair_value (+ sop_breakdown) and risk_reward (downside-to-break vs upside-to-fair); judge the operating position vs the verified figures; sanity-check the multiple against the chain_map true_competitors. Produce verdict (A/B/C), conviction (int 1-5), consensus_delta, valley_of_death, positioning_washout, forcing_function, moderator_conclusion. THEN, separately, value_conviction (int 1-5): the value case judged on valuation vs the SoP fair value + forensic quality ONLY. The two scores MUST be allowed to diverge.\n' +
    '6b. TYPED VALUATION BLOCK (MANDATORY - the numbers the pipeline checks and sizes on): distill your reconciliation into POINT NUMBERS per share, in the quote currency: bear_px (your adverse case - ONE number; your ranges stay in the prose), base_fv_px (base case), bull_px (favorable case), downside_floor_px (ONLY a structural floor - deal terms, net cash/share, tender; else null - a chart low or a dividend yield is NOT a floor), valuation_method ("sop"|"multiple"|"spread"|"recovery"), horizon_months (when the base case lands). ORDERING bear_px <= base_fv_px <= bull_px is REQUIRED. State LEVELS only: risk_reward ratios, expected-return %, and MoS % are COMPUTED BY THE PIPELINE from these numbers - any "N:1" or %-vs-% arithmetic you assert in prose will be overwritten by the computed values.\n' +
    '7. Write (Write tool) VALID, escaped JSON to ' + RES + '/' + sym + '.json with: symbol(="' + sym + '"), sector, signal_type(="mining"), chains(array, from chain_map), business_model, value_chain_position, live_price(number - the price you actually used), price_currency, valuation({live_price, price_currency, quote_listing(="' + sym + '"), bear_px, base_fv_px, bull_px, downside_floor_px, valuation_method, horizon_months, as_of(today YYYY-MM-DD)} - the step-6b numbers), cost_curve_verified(one line: proxy vs company-reported figure, agree/disagree), gm_trajectory(one line: gross-margin direction on revenue direction, with the numbers), bull_thesis, bear_thesis, sop_bull, sop_bear, sop_fair_value, sop_breakdown, risk_reward, catalyst_status(EXACTLY one bare enum token: FIRED|ARB|PENDING_HARD|SOFT_EXTENDED|UNVERIFIABLE - NO prose), catalyst_status_note(the dated evidence prose), peer_comps_note, verdict, conviction, value_conviction(int), consensus_delta, valley_of_death, positioning_washout, forcing_function, moderator_conclusion, interrogator_score(int), trajectory, source(="' + (online ? 'opus_mining_online' : 'opus_mining_mod') + '"), transcript_source(="' + (online ? 'web' : 'fmp') + '").\n' +
    'Reply exactly: DONE'
}

const ALL = SYMS.map(s => ({ sym: s, online: false }))
  .concat(ONLINE_SYMS.map(s => ({ sym: s, online: true })))
log(`Mining Lane A debate over ${ALL.length} names (${SYMS.length} FMP + ${ONLINE_SYMS.length} online-fetch); Director runs separately after mining-input.`)
phase('Debate')
const BATCH = 8   // rate-limit safety: run 8 web-heavy agents at a time (429s).
for (let b = 0; b < ALL.length; b += BATCH) {
  log(`Debate batch ${Math.floor(b / BATCH) + 1}/${Math.ceil(ALL.length / BATCH)} (names ${b + 1}-${Math.min(b + BATCH, ALL.length)} of ${ALL.length})`)
  await parallel(ALL.slice(b, b + BATCH).map(it => () => agent(
    debatePrompt(it.sym, it.online),
    { label: 'mining:' + it.sym + (it.online ? '(web)' : ''), phase: 'Debate', agentType: 'general-purpose', model: 'opus' })))
}
// NO in-workflow Director: the Director grades the grade-input file, which `mining-input` builds
// from THESE debate results AFTER this workflow (sequence: Workflow -> mining-numeric-gate
// --enforce -> mining-input -> Director agent -> mining-skeptic -> Workflow -> mining-post).
log('Mining debate complete (Director runs separately after mining-input).')
return 'DONE'
