#!/usr/bin/env python3
"""Basket 13 — export the tracker to the frontend data module.

Reads _basket13_tracker.json (+ _basket13_out.json for the CRO conditions/entry limits)
and writes frontend/app/data/basket13.ts — the module the Catalyst Watch page imports.
Re-run after every inject/resolve, then ship via the §10 publishing flow (the data is
baked into the bundle, same as the board).

Usage: python _basket13_export.py
"""
import json, os, datetime

BASE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(BASE)
TRK = os.path.join(BASE, "_basket13_tracker.json")
OUTJ = os.path.join(BASE, "_basket13_out.json")
TS = os.path.join(ROOT, "frontend", "app", "data", "basket13.ts")

# mirror of the inject cap dials, displayed as "n / cap" in the UI
MAX_PER_DRIVER, MAX_SUPER_PCT, MAX_NAMES = 2, 40.0, 20
MAX_PER_LANE = {"bio_convergence": 5}
MAX_WATCHLIST, MAX_WATCHLIST_PER_DRIVER = 10, 5


def main():
    t = json.load(open(TRK, encoding="utf-8"))
    cro_cond, cro_check = {}, {}
    if os.path.exists(OUTJ):
        out = json.load(open(OUTJ, encoding="utf-8"))
        for v in out.get("cro") or []:
            if v.get("symbol"):
                cro_cond[v["symbol"]] = v.get("conditions") or []
                cro_check[v["symbol"]] = v.get("live_edge_check") or ""

    entries = []
    for e in t["entries"]:
        d = dict(e)
        det = e.get("cro_detail") or {}                       # self-contained: prefer the entry's stored CRO detail
        d["cro_conditions"] = det.get("conditions") or cro_cond.get(e["symbol"], [])
        d["cro_live_edge_check"] = det.get("live_edge_check") or cro_check.get(e["symbol"], "")
        # expected return % on the UNDERLYING (comparable with the live/realized marks):
        # binaries -> the CRO's recomputed EV; ratio names -> move to the fair-value target.
        # Pending (resting-limit) seats price the expectation off the LIMIT (the only fill price).
        basis = d.get("entry_price") or d.get("limit_price")
        if isinstance(d.get("expected_ev"), (int, float)):
            d["expected_return_pct"] = round(d["expected_ev"] * 100, 1)
        elif d.get("fair_value_target") and basis:
            d["expected_return_pct"] = round((d["fair_value_target"] / basis - 1) * 100, 1)
        else:
            d["expected_return_pct"] = None
        entries.append(d)

    unresolved = [e for e in entries if not e.get("resolution")]
    opene = [e for e in unresolved if e.get("status") != "PENDING_LIMIT"]
    pend = [e for e in unresolved if e.get("status") == "PENDING_LIMIT"]
    drv, clus, lanes = {}, {}, {}
    for e in unresolved:                # caps count pending as-if-filled
        drv[e["resolution_driver"]] = drv.get(e["resolution_driver"], 0) + 1
        clus[e["super_cluster"]] = round(clus.get(e["super_cluster"], 0.0) + (e["weight_pct"] or 0), 2)
        lanes[e.get("lane_canon")] = lanes.get(e.get("lane_canon"), 0) + 1
    invested = round(sum(e["weight_pct"] or 0 for e in opene), 2)
    pending_w = round(sum(e["weight_pct"] or 0 for e in pend), 2)

    payload = {
        "generated": datetime.date.today().isoformat(),
        "invested_pct": invested,
        "pending_pct": pending_w,
        "cash_pct": round(100 - invested - pending_w, 2),
        "caps": {"max_per_driver": MAX_PER_DRIVER, "max_super_pct": MAX_SUPER_PCT, "max_names": MAX_NAMES,
                 "max_per_lane": MAX_PER_LANE, "max_watchlist": MAX_WATCHLIST,
                 "max_watchlist_per_driver": MAX_WATCHLIST_PER_DRIVER,
                 "risk_to_floor_pct": 1.5, "binary_premium_pct": 2.0},
        "driver_utilization": dict(sorted(drv.items(), key=lambda kv: -kv[1])),
        "cluster_utilization": dict(sorted(clus.items(), key=lambda kv: -kv[1])),
        "lane_utilization": dict(sorted(lanes.items(), key=lambda kv: -kv[1])),
        "entries": entries,
        "watchlist": t.get("watchlist", []),    # on-deck: cap-blocked-but-wanted (renders below the basket)
        "watchlist_marks": t.get("watchlist_marks", []),   # on-deck equal-weight cohort NAV series (separate track record)
        "non_selections": t.get("non_selections", []),
        "runs": t.get("runs", []),
        "marks": t.get("marks", []),    # daily NAV series (_basket13_mark.py) — the track record
        "memo": (t.get("runs") or [{}])[-1].get("memo", ""),
    }
    hdr = ("// Basket 13 — Catalyst sleeve (paper, event-resolution tracker view).\n"
           "// AUTO-GENERATED by backend/_basket13_export.py — do not hand-edit.\n")
    open(TS, "w", encoding="utf-8").write(
        hdr + f"export const BASKET13: any = {json.dumps(payload, ensure_ascii=False)};\n")
    res = [e for e in entries if e.get("resolution")]
    print(f"EXPORTED basket13.ts: {len(opene)} open + {len(res)} resolved entries, "
          f"{len(payload['non_selections'])} non-selections, invested {invested}%  -> {os.path.relpath(TS, ROOT)}")


if __name__ == "__main__":
    main()
