#!/usr/bin/env python
# Catalyst sweep loop engine. Modes:
#   python _sweep_pipe.py gen <n>          -> write chunk n's workflow .js (ASCII-folded; n==1 also
#                                             snapshots the board to .bak and starts a fresh run manifest)
#   python _sweep_pipe.py harvest <task_output.json> <n>
#                                          -> extract the Workflow result into chunk<n>.json + register
#                                             it in the run manifest (replaces hand-copying the result)
#   python _sweep_pipe.py compose          -> gate-checked ATOMIC board build from this run's harvested
#                                             chunks. The live board is never blanked mid-run: a failed
#                                             or degraded sweep simply never composes, and the prior
#                                             board stays untouched (kills the 2026-08-18 hazards:
#                                             mid-run [] reset + stale prior-run chunk JSONs).
#   python _sweep_pipe.py inject <chunk_output.json>
#                                          -> legacy per-chunk accumulate (kept for gap-fills)
#   python _sweep_pipe.py genlist <tag> <SYM,SYM,...>
import json, sys, os, unicodedata, datetime

BASE = 'C:/Users/Bruno/Stock-Screener'
UNIVERSE_F = f'{BASE}/backend/_sweep_universe.json'
BOARD_F    = f'{BASE}/backend/_sweep_board.json'
BAK_F      = f'{BASE}/backend/_sweep_board.bak.json'
MANIFEST_F = f'{BASE}/backend/_sweep_results/_run_manifest.json'
TS_F       = f'{BASE}/frontend/app/data/catalystBoardSweep.ts'
SIZE = 150
MAX_FAILED_CHUNKS = 2     # compose gate: more than this many un-harvested chunks -> abort
MIN_FRESH_RATIO   = 0.6   # compose gate: fresh board must be >= this fraction of the prior board

# The Workflow permission validator rejects non-ASCII in generated .js (it misreads UTF-8 as C1
# controls) — every run before 2026-08-19 hand-folded the files after a failed launch. Fold at
# generation instead: NFKD-strip accents (company-name cosmetics only; tickers are ASCII).
_FOLD = {'\u2014': '-', '\u2013': '-', '\u2018': "'", '\u2019': "'", '\u201c': '"', '\u201d': '"',
         '\u2264': '<=', '\u2265': '>=', '\u00b1': '+/-', '\u2500': '-', '\u2192': '->', '\u00a0': ' '}
def _ascii_fold(s):
    out = []
    for ch in unicodedata.normalize('NFKD', s):
        if ord(ch) < 128:
            out.append(ch)
        else:
            out.append(_FOLD.get(ch, ''))
    return ''.join(out)

def _load_manifest():
    try:
        return json.load(open(MANIFEST_F, encoding='utf-8'))
    except (FileNotFoundError, ValueError):
        return None

def _save_manifest(m):
    json.dump(m, open(MANIFEST_F, 'w', encoding='utf-8'), indent=1)

TS_TEMPLATE = r'''// Catalyst Watch — SWEEP results (full-universe Opus-4.8 3-tier sweep, rolling chunks from 2026-06-06).
// AUTO-GENERATED by backend/_sweep_pipe.py — do not hand-edit.
const NO_OPTIONS = (note: any) => ({ iv_current:null, skew_25d:null, term_structure:"N/A", pc_oi_ratio:null, total_oi:null, implied_earnings_move_pct:null, market_sentiment_flag:"N/A", overall_interpretation:note });
const S = "2026-06-06T12:00:00Z";
function sweepDossier(r: any): any {
  return {
    symbol:r.symbol, company_name:r.company_name||r.symbol, price:r.price??null, market_cap:r.market_cap??null,
    catalyst_density_score:r.score, adjusted_loeb_score:r.score, final_adjusted_loeb:r.score,
    upside_downside_ratio:r.rr??null, catalyst_nature:"pricing_dislocation", re_rate_status:"pending",
    tier:r.tier, lane:r.lane, gate_status:r.gate||"PASS", bloom_gates_passed:r.bloom_gates?[r.bloom_gates]:[],
    edge:r.edge||"", verify_verdict:r.verdict||"(sweep)", instrument:r.instrument||"", resolution_driver:r.resolution_driver||"",
    analysis_summary:"[SWEEP "+(r.chunk||"")+"] "+(r.analysis||r.catalyst||""),
    bloom_catalysts:{ catalyst_1:{title:"Catalyst",detected:true,description:r.catalyst||"",evidence:r.primary_source||""}, catalyst_2:{title:"Milestone",detected:!!r.dated_milestone,description:r.dated_milestone||"",evidence:""}, catalyst_3:{title:"Verify",detected:r.verdict==="CONFIRMED",description:r.verdict||"",evidence:r.kill_fact||""} },
    loeb_criteria:{ catalyst_density:{rating:r.edge||"Medium",analysis:r.analysis||r.catalyst||""}, sum_of_parts:{detected:false,analysis:""}, activism_potential:{detected:(r.lane||"").includes("activist"),analysis:""}, risk_reward:{ratio:r.rr?(r.rr+":1"):null,analysis:r.bull_base_bear||""} },
    options_signals:r.options_signals||NO_OPTIONS("Sweep dossier; options not pulled."),
    recent_events:[{date:"2026-06-06",type:"filing",title:r.catalyst||"Sweep-verified catalyst",link:r.primary_source||""}],
    cache_timestamp:S,
  };
}
const SWEEP_RAW: any[] = __SWEEP_RAW__;
export const CATALYST_BOARD_SWEEP: Record<string, any> = Object.fromEntries(SWEEP_RAW.map((r:any)=>[r.symbol, sweepDossier(r)]));
export const CATALYST_CANDIDATES_SWEEP: any[] = Object.values(CATALYST_BOARD_SWEEP).map((d:any)=>({ symbol:d.symbol, name:d.company_name, price:d.price??null, market_cap:d.market_cap??null, catalyst_score:d.catalyst_density_score, adjusted_loeb_score:d.adjusted_loeb_score, flags:[d.tier,d.lane].filter(Boolean), has_special_flag:d.tier==="ACTIVE", categories:[d.lane], rr_ratio:d.upside_downside_ratio??null, is_scanned:true, convergence_score:null }));
'''

JS_TEMPLATE = r'''export const meta = {
  name: 'catalyst-sweep-c__N__',
  description: 'Opus 3-tier catalyst sweep (chunk __LABEL__): scan -> deep -> skeptic',
  phases: [ { title:'Scan', model:'opus' }, { title:'Deep', model:'opus' }, { title:'Skeptic', model:'opus' } ],
}
const UNIVERSE = __NAMES__
const BATCH = 25
const DEEP_T = 5.0
const SCAN_SCHEMA = { type:'object', properties:{ names:{ type:'array', items:{ type:'object', properties:{ symbol:{type:'string'}, score:{type:'number'}, tier:{type:'string', enum:['ACTIVE','WATCH','NONE']}, lane:{type:'string'}, dated_catalyst:{type:'boolean'}, fired:{type:'boolean'}, one_line:{type:'string'} }, required:['symbol','score','tier','dated_catalyst','fired','one_line'] } } }, required:['names'] }
const DEEP_SCHEMA = { type:'object', properties:{ symbol:{type:'string'}, score:{type:'number'}, tier:{type:'string', enum:['ACTIVE','WATCH','NONE']}, lane:{type:'string'}, catalyst:{type:'string'}, dated_milestone:{type:'string'}, fired:{type:'boolean'}, instrument:{type:'string'}, bloom_gates:{type:'string'}, edge:{type:'string'}, analysis:{type:'string'}, primary_source:{type:'string'},
  // Phase-2 valuation (OPTIONAL on the fast sweep tier; the full SoP build is the dedicated valuation dossier).
  valuation_method:{type:'string', enum:['sop','spread','binary_prob','recovery','capital_return']}, fair_value_target:{type:'number'}, downside_floor:{type:'number'}, reference_price:{type:'number'}, reference_rr:{type:'number'}, valuation_basis:{type:'string'}, advocacy_target:{type:'number'} }, required:['symbol','score','tier','catalyst','fired','analysis'] }
const VERDICT_SCHEMA = { type:'object', properties:{ symbol:{type:'string'}, verdict:{type:'string', enum:['CONFIRMED','CONFIRMED_WITH_CORRECTIONS','REFUTED']}, final_score:{type:'number'}, kill_fact:{type:'string'}, confidence:{type:'string'} }, required:['symbol','verdict','final_score'] }
function scanPrompt(b){ return `Today is __TODAY__. SCAN (triage) tier of a catalyst sweep for an event-driven / special-situations book. Verify live (WebSearch + FMP MCP via ToolSearch). For EACH name do a FAST triage (a couple of quick checks; do NOT deep-dive): does it have a REAL, DATED, FORWARD special-situation catalyst? Types: M&A / complicated merger-arb; spin-off; forced-seller OVERHANG clearing (own the suppressed underlying); distressed/restructuring/LME with a dated milestone; activist+structural (hardening trigger); capital-return (tender/special-div/dated deleveraging); supply-shortage+timing-moat; or a dated binary (PDUFA/ruling) WITH mispriced asymmetry.
GATE HARD: most names have NO near-term catalyst -> score 0-3, tier NONE. FORWARD-not-fired (already happened/re-rated => fired=true). NOT a macro bet. Rubric DEFAULT LOW: 0-2 none; 3-4 vague/priced/fired; 5-6 one real dated catalyst; 7-8 strong dated >=2 Bloom gates; 9-10 multiple imminent hard.
ENTRY-ARC (this pipeline is bi-weekly — it cannot win day-of events): prefer EARLY-ARC setups where the catalyst just became knowable and the price has NOT yet moved (thin coverage, no re-rate) over late-arc names that are fully run and days from resolution. A name up big into an imminent binary is 3-4 (priced) even if the event is real; a fresh, unmoved, months-out structural setup outranks a famous next-week binary.
Return for EACH {symbol, score, tier, lane, dated_catalyst, fired, one_line}. Ruthless and fast; most should be NONE.
NAMES (${b.length}): ${JSON.stringify(b)}` }
function deepPrompt(n){ return `Today is __TODAY__. DEEP tier. Verify ${n.symbol} (${n.company_name||''}). Triage flagged: "${n.one_line}" (tier ${n.tier}, score ${n.score}, lane ${n.lane||'?'}). Do FOCUSED verification — AT MOST ~6 lookups (WebSearch/WebFetch + FMP via ToolSearch), cite source+date. Gate STRICTLY: real+specific (Bloom G1 named counterparty / G2 concrete commitment / G3 specific currently-unpriced figure) + DATED + FORWARD (not fired/not re-rated) + NOT a macro bet.
NUMERATOR PROVENANCE (mandatory when the upside is DERIVED rather than contractual — deleveraging/SoP/spin/restructuring/asset-sale lanes; a cash deal price is contractual and exempt): the upside figure must be re-derived from the capital structure, never inherited from an analyst target. Spend one lookup on the latest 10-Q/10-K: preferred stock ahead of the common at REDEMPTION value incl. PIK accrual (not balance-sheet carry), where sale proceeds are contractually required to go, external-manager fee incentives. If the equity waterfall cannot support the flagged upside, score the EQUITY, not the EVENT (cap score 4). Lesson instance: FIP 2026-07 — deal certain to close, but a $1.6B pref stack (carried $1.12B) left mechanical common SoP negative; the inherited $9 target was never re-derived.
RESIDUAL CAPTURE (mandatory, ALL lanes): UNFIRED does not mean UNPRICED. Quantify what is still on the table: (a) the run-up from the pre-catalyst base (price before the event became publicly knowable) to today; (b) the remaining % from today's price to the provenance-checked favorable-resolution value. An event can be 100% forward and 90% harvested (VISN 2026-07: second distribution undeclared yet fully priced — buying the receipt, not the gain; SLS 2026-07: +55% pre-event). Score on REMAINING capture, not event quality: mostly-harvested => cap score 4 regardless of how real and certain the event is. State both numbers (run-up %, remaining %) inside the edge field.
CRITICAL: your ONLY deliverable is a SINGLE StructuredOutput call (no prose report). After ~6 lookups, STOP and call StructuredOutput; if not fully verifiable, still call it with your best assessment + note the gap in analysis. Fields {symbol, score (0-10), tier (ACTIVE/WATCH/NONE), lane, catalyst (1 sentence), dated_milestone (+next date), fired, instrument, bloom_gates (which of G1/G2/G3), edge (H/M/L+why), analysis (2-3 sentences), primary_source (+date)}. No real dated forward catalyst => tier NONE, score <=3.` }
function skepticPrompt(d){ return `Today is __TODAY__. SKEPTIC tier. KILL this line; default REFUTED if you cannot independently confirm the load-bearing facts against a PRIMARY source. Verify live. Attack: (1) FIRED-not-forward; (2) date accuracy; (3) terms/magnitude truth; (4) thesis weakness (real edge vs priced/wrong/story); (5) tradeability + hidden disqualifier; (6) NUMERATOR PROVENANCE — when the upside is derived (SoP/deleveraging/asset-sale/spin), re-derive what the event delivers TO THE COMMON from primary filings: pref redemption value + PIK step-ups vs carrying value, proceeds-use language ("reinvestment"/"growth" = proceeds may never reach holders), external-manager fees paid on assets not returns; an upside inherited from an analyst target with no waterfall check = cut the score hard or REFUTE; (7) ALREADY-HARVESTED — compute the run-up from the pre-catalyst base and the remaining distance to the modeled value; if the bulk of the payoff was captured before today (announcement re-rate, price ~= consensus target, 52wk-high proximity into the event), cut the score hard REGARDLESS of how certain the event is — unfired is not unpriced.
CRITICAL: your ONLY deliverable is a SINGLE StructuredOutput call (no prose). After ~6 lookups, call it.
LINE: ${d.symbol} — ${d.catalyst} | tier ${d.tier}, score ${d.score}, instrument: ${d.instrument||'?'} | ${d.analysis||''}
Fields {symbol, verdict (CONFIRMED/CONFIRMED_WITH_CORRECTIONS/REFUTED), final_score (0-10), kill_fact, confidence (H/M/L)}.` }
// retry transient errors (529 Overloaded / rate limits); only retries on THROW, passes nulls through, rethrows after n tries (parallel catches -> null, recoverable by resume)
async function aR(p,o,n){ n=n||6; let e; for(let t=0;t<n;t++){ try{ return await agent(p,o) }catch(err){ e=err } } throw e }
phase('Scan')
const batches=[]; for(let i=0;i<UNIVERSE.length;i+=BATCH) batches.push(UNIVERSE.slice(i,i+BATCH))
log(`Scanning ${UNIVERSE.length} names in ${batches.length} batches of ${BATCH} (Opus)`)
const scanned=(await parallel(batches.map((b,bi)=>()=>aR(scanPrompt(b),{label:`scan:b${bi}`,phase:'Scan',schema:SCAN_SCHEMA,model:'opus'})))).filter(Boolean).flatMap(r=>(r&&r.names)||[])
const survivors=scanned.filter(n=>n&&n.tier!=='NONE'&&n.score>=DEEP_T&&n.dated_catalyst&&!n.fired)
const dist={active:scanned.filter(n=>n.tier==='ACTIVE').length,watch:scanned.filter(n=>n.tier==='WATCH').length,none:scanned.filter(n=>n.tier==='NONE').length}
log(`Scan done: ${scanned.length} scored (A ${dist.active}/W ${dist.watch}/N ${dist.none}) -> ${survivors.length} survivors`)
phase('Deep')
const DEEP_CONC=4
const results=[]
for(let di=0;di<survivors.length;di+=DEEP_CONC){
  const sub=survivors.slice(di,di+DEEP_CONC)
  const subRes=await parallel(sub.map(s=>()=>aR(deepPrompt(s),{label:`deep:${s.symbol}`,phase:'Deep',schema:DEEP_SCHEMA,model:'opus'}).then(deep=>{ if(!deep) return null; if(deep.tier==='ACTIVE'&&!deep.fired){ return aR(skepticPrompt(deep),{label:`skeptic:${deep.symbol}`,phase:'Skeptic',schema:VERDICT_SCHEMA,model:'opus'}).then(v=>({...deep,verify:v,final_score:(v&&typeof v.final_score==='number')?v.final_score:deep.score})) } return {...deep,verify:null,final_score:deep.score} })))
  results.push(...subRes)
}
const verified=results.filter(Boolean)
const activeVerified=verified.filter(r=>r.tier==='ACTIVE'&&(!r.verify||r.verify.verdict!=='REFUTED'))
log(`Deep+Skeptic done: ${verified.length} dossiers; ${activeVerified.length} verified ACTIVE`)
return { chunk:'__LABEL__', scanned:scanned.length, scan_distribution:dist,
  survivors_flagged:survivors.map(s=>({symbol:s.symbol,score:s.score,tier:s.tier,lane:s.lane,one_line:s.one_line})),
  verified:verified.map(r=>({symbol:r.symbol,score:r.final_score,tier:r.tier,lane:r.lane,catalyst:r.catalyst,dated_milestone:r.dated_milestone,instrument:r.instrument,bloom_gates:r.bloom_gates,edge:r.edge,primary_source:r.primary_source,verdict:r.verify?r.verify.verdict:null,kill_fact:r.verify?r.verify.kill_fact:null,analysis:r.analysis})),
}'''

def regen_ts(board):
    raw = json.dumps(board, ensure_ascii=False)
    open(TS_F, 'w', encoding='utf-8').write(TS_TEMPLATE.replace('__SWEEP_RAW__', raw))

def inject(chunk_file):
    uni = {x['symbol']: x for x in json.load(open(UNIVERSE_F, encoding='utf-8'))}
    board = json.load(open(BOARD_F, encoding='utf-8')) if os.path.exists(BOARD_F) else []
    by_sym = {b['symbol']: b for b in board}
    d = json.load(open(chunk_file, encoding='utf-8'))
    res = d.get('result', d)
    label = res.get('chunk', '')
    added = []
    for v in res.get('verified', []):
        tier = v.get('tier'); score = v.get('score') or 0
        if tier in ('ACTIVE', 'WATCH') and score >= 4:
            sym = v['symbol']
            by_sym[sym] = {
                'symbol': sym, 'company_name': uni.get(sym, {}).get('company_name', sym),
                'score': score, 'tier': tier, 'lane': v.get('lane', ''), 'catalyst': v.get('catalyst', ''),
                'dated_milestone': v.get('dated_milestone', ''), 'instrument': v.get('instrument', ''),
                'bloom_gates': v.get('bloom_gates', ''), 'edge': v.get('edge', ''), 'analysis': v.get('analysis', ''),
                'primary_source': v.get('primary_source', ''), 'verdict': v.get('verdict') or '',
                'kill_fact': v.get('kill_fact') or '', 'chunk': label,
            }
            added.append(f"{sym}({score},{tier})")
    board = sorted(by_sym.values(), key=lambda b: -(b.get('score') or 0))
    json.dump(board, open(BOARD_F, 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
    regen_ts(board)
    print(f"INJECTED {len(added)} from chunk '{label}': {', '.join(added)}")
    print(f"BOARD now {len(board)} sweep names")

def gen(n):
    uni = json.load(open(UNIVERSE_F, encoding='utf-8'))
    chunk = uni[(n-1)*SIZE : n*SIZE]
    if not chunk:
        print(f"NO_MORE_CHUNKS (n={n}, universe={len(uni)})"); return
    if n == 1:
        # a new sweep run: snapshot the live board (compose's gate baseline) and reset the
        # manifest. The board itself is NOT touched — it stays live until compose passes.
        if os.path.exists(BOARD_F):
            prev = json.load(open(BOARD_F, encoding='utf-8'))
            json.dump(prev, open(BAK_F, 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
            print(f"SNAPSHOT {len(prev)} names -> _sweep_board.bak.json")
        _save_manifest({'run_date': datetime.date.today().isoformat(),
                        'universe': len(uni), 'expected': [], 'harvested': {}})
        print("MANIFEST reset for a new run")
    m = _load_manifest()
    if m is None:
        print("WARN: no run manifest (gen 1 not run first?) — creating one mid-run")
        m = {'run_date': datetime.date.today().isoformat(), 'universe': len(uni),
             'expected': [], 'harvested': {}}
    if n not in m['expected']:
        m['expected'].append(n); _save_manifest(m)
    names = [{'symbol': x['symbol'], 'company_name': x['company_name']} for x in chunk]
    label = f"{n} ({chunk[0]['symbol']}-{chunk[-1]['symbol']})"
    js = (JS_TEMPLATE.replace('__N__', str(n)).replace('__NAMES__', json.dumps(names, ensure_ascii=False))
          .replace('__LABEL__', label).replace('__TODAY__', datetime.date.today().isoformat()))
    js = _ascii_fold(js)
    out = f'{BASE}/backend/_sweep_results/chunk{n}_workflow.js'
    open(out, 'w', encoding='ascii', newline='\n').write(js)
    print(f"WROTE {out} ({len(names)} names, label '{label}', ASCII-folded)")
    print(out)


def harvest(task_file, n):
    """Extract a Workflow tool's task-output JSON into chunk<n>.json + register in the manifest."""
    d = json.load(open(task_file, encoding='utf-8'))
    res = d.get('result', d)
    if not isinstance(res, dict) or 'verified' not in res:
        print(f"CHUNK {n} FAILED: no usable result object (keys={list(d)[:8]})"); sys.exit(1)
    out = f'{BASE}/backend/_sweep_results/chunk{n}.json'
    json.dump(res, open(out, 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
    kept = [v for v in res.get('verified', [])
            if v.get('tier') in ('ACTIVE', 'WATCH') and (v.get('score') or 0) >= 4]
    m = _load_manifest()
    if m is None:
        print("WARN: no run manifest — harvest recorded to disk only")
    else:
        m['harvested'][str(n)] = {'scanned': res.get('scanned', 0),
                                  'flagged': len(res.get('survivors_flagged', [])),
                                  'verified': len(res.get('verified', [])), 'kept': len(kept)}
        _save_manifest(m)
    print(f"HARVESTED chunk {n}: scanned={res.get('scanned')} verified={len(res.get('verified', []))} -> {len(kept)} keepable")
    print(f"WROTE {out}")


def compose():
    """Gate-checked atomic board build from THIS run's harvested chunks only."""
    m = _load_manifest()
    if m is None:
        print("ABORT: no run manifest — nothing to compose (run gen 1 first)"); sys.exit(1)
    expected  = sorted(m.get('expected', []))
    harvested = sorted(int(k) for k in m.get('harvested', {}))
    failed = [n for n in expected if n not in harvested]
    if len(failed) > MAX_FAILED_CHUNKS:
        print(f"ABORT: {len(failed)} chunks un-harvested {failed} (limit {MAX_FAILED_CHUNKS}) — "
              "prior board left untouched"); sys.exit(1)
    uni = {x['symbol']: x for x in json.load(open(UNIVERSE_F, encoding='utf-8'))}
    by = {}
    for n in harvested:
        res = json.load(open(f'{BASE}/backend/_sweep_results/chunk{n}.json', encoding='utf-8'))
        label = res.get('chunk', str(n))
        for v in res.get('verified', []):
            if v.get('tier') in ('ACTIVE', 'WATCH') and (v.get('score') or 0) >= 4:
                s = v['symbol']
                by[s] = {'symbol': s, 'company_name': uni.get(s, {}).get('company_name', s),
                         'score': v.get('score'), 'tier': v.get('tier'), 'lane': v.get('lane', ''),
                         'catalyst': v.get('catalyst', ''), 'dated_milestone': v.get('dated_milestone', ''),
                         'instrument': v.get('instrument', ''), 'bloom_gates': v.get('bloom_gates', ''),
                         'edge': v.get('edge', ''), 'analysis': v.get('analysis', ''),
                         'primary_source': v.get('primary_source', ''), 'verdict': v.get('verdict') or '',
                         'kill_fact': v.get('kill_fact') or '', 'chunk': label}
    prev_n = 0
    if os.path.exists(BAK_F):
        prev_n = len(json.load(open(BAK_F, encoding='utf-8')))
    if prev_n and len(by) < MIN_FRESH_RATIO * prev_n:
        print(f"ABORT: fresh board {len(by)} < {MIN_FRESH_RATIO} x prev {prev_n} = "
              f"{MIN_FRESH_RATIO*prev_n:.0f} — sweep materially degraded, prior board left untouched")
        sys.exit(1)
    board = sorted(by.values(), key=lambda b: -(b.get('score') or 0))
    tmp = BOARD_F + '.tmp'
    json.dump(board, open(tmp, 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
    os.replace(tmp, BOARD_F)           # atomic: the live board is never half-written
    regen_ts(board)
    old = {x['symbol'] for x in json.load(open(BAK_F, encoding='utf-8'))} if prev_n else set()
    new = set(by)
    print(f"COMPOSED board: {len(board)} names ({prev_n} before) | chunks {len(harvested)}/{len(expected)}"
          f"{' | FAILED: ' + str(failed) if failed else ''}")
    print(f"  entered ({len(new-old)}): {' '.join(sorted(new-old)) or '-'}")
    print(f"  dropped ({len(old-new)}): {' '.join(sorted(old-new)) or '-'}")

def genlist(tag, syms):
    # gap-fill: build a workflow for an arbitrary ticker list (rate-limit losses, remaps, ad-hoc).
    uni = {x['symbol']: x for x in json.load(open(UNIVERSE_F, encoding='utf-8'))}
    miss = [s for s in syms if s not in uni]
    if miss: print(f"WARN not in universe (skipped): {miss}")
    syms = [s for s in syms if s in uni]
    names = [{'symbol': s, 'company_name': uni[s]['company_name']} for s in syms]
    label = f"gapfill-{tag} ({len(names)} names)"
    js = (JS_TEMPLATE.replace('__N__', tag).replace('__NAMES__', json.dumps(names, ensure_ascii=False))
          .replace('__LABEL__', label).replace('__TODAY__', datetime.date.today().isoformat()))
    js = _ascii_fold(js)
    out = f'{BASE}/backend/_sweep_results/gapfill_{tag}_workflow.js'
    open(out, 'w', encoding='ascii', newline='\n').write(js)
    print(f"WROTE {out} ({len(names)} names: {[n['symbol'] for n in names]}, label '{label}', ASCII-folded)")
    print(out)

if __name__ == '__main__':
    mode = sys.argv[1]
    if mode == 'inject': inject(sys.argv[2])
    elif mode == 'gen': gen(int(sys.argv[2]))
    elif mode == 'harvest': harvest(sys.argv[2], int(sys.argv[3]))
    elif mode == 'compose': compose()
    elif mode == 'genlist': genlist(sys.argv[2], [s.strip().upper() for s in sys.argv[3].split(',') if s.strip()])
    else: print(f"unknown mode '{mode}' (gen | harvest | compose | inject | genlist)"); sys.exit(2)
