export const meta = {
  name: 'value-skeptic',
  description: 'Independent skeptic kill-tier over the value-apex finalists (default REFUTED)',
  phases: [{ title: 'Skeptic', model: 'fable' }],
}
const DIR = 'backend/_opus_debate'
const SYMS = ["EEFT", "WKL.AS", "UHS", "CTSH", "NTES", "HRB", "SCR.PA", "LNC", "THC", "HRMY", "ADBE", "DECK", "BKNG", "KBR", "FGR.PA", "CMCSA"]
const MOAT_HINTS = {"EEFT": {"erosion": "", "severity": "none", "roic_below": true, "returns_trend": "rising", "gross_margin_trend": "expanding", "refute_candidate": false}, "WKL.AS": {"erosion": "", "severity": "none", "roic_below": false, "returns_trend": "rising", "gross_margin_trend": "stable", "refute_candidate": false}, "UHS": {"erosion": "", "severity": "none", "roic_below": false, "returns_trend": "rising", "gross_margin_trend": "stable", "refute_candidate": false}, "CTSH": {"erosion": "", "severity": "none", "roic_below": false, "returns_trend": "stable", "gross_margin_trend": "stable", "refute_candidate": false}, "NTES": {"erosion": "", "severity": "none", "roic_below": false, "returns_trend": "rising", "gross_margin_trend": "expanding", "refute_candidate": false}, "HRB": {"erosion": "", "severity": "none", "roic_below": false, "returns_trend": "rising", "gross_margin_trend": "stable", "refute_candidate": false}, "SCR.PA": {"erosion": "", "severity": "none", "roic_below": true, "returns_trend": "rising", "gross_margin_trend": "stable", "refute_candidate": false}, "LNC": {"erosion": "", "severity": "none", "roic_below": true, "returns_trend": "rising", "gross_margin_trend": "expanding", "refute_candidate": false}, "THC": {"erosion": "CAP", "severity": "eroding", "roic_below": false, "returns_trend": "falling", "gross_margin_trend": "expanding", "refute_candidate": false}, "HRMY": {"erosion": "", "severity": "none", "roic_below": false, "returns_trend": "rising", "gross_margin_trend": "eroding", "refute_candidate": false}, "ADBE": {"erosion": "CAP", "severity": "eroding", "roic_below": false, "returns_trend": "falling", "gross_margin_trend": "stable", "refute_candidate": false}, "DECK": {"erosion": "", "severity": "none", "roic_below": false, "returns_trend": "rising", "gross_margin_trend": "stable", "refute_candidate": false}, "BKNG": {"erosion": "", "severity": "none", "roic_below": false, "returns_trend": "rising", "gross_margin_trend": "stable", "refute_candidate": false}, "KBR": {"erosion": "", "severity": "none", "roic_below": false, "returns_trend": "rising", "gross_margin_trend": "stable", "refute_candidate": false}, "FGR.PA": {"erosion": "CAP", "severity": "eroding", "roic_below": true, "returns_trend": "rising", "gross_margin_trend": "eroding", "refute_candidate": true}, "CMCSA": {"erosion": "CAP", "severity": "eroding", "roic_below": true, "returns_trend": "rising", "gross_margin_trend": "stable", "refute_candidate": true}}
phase('Skeptic')
const BATCH = 8
for (let b = 0; b < SYMS.length; b += BATCH) {
  await parallel(SYMS.slice(b, b + BATCH).map(sym => () => agent(
    'SKEPTIC tier for ' + sym + ' (value-apex finalist). Your job is to KILL this value thesis; default verdict REFUTED unless you can independently confirm the load-bearing facts against a PRIMARY source (filings, the company IR site, regulator pages). You see ONLY the bear side — do NOT read or reconstruct the bull case.\n' +
    ((MOAT_HINTS[sym] || {}).refute_candidate ? 'MOAT ALERT (deterministic screen): ' + sym + ' is a TERMINAL-EROSION candidate — erosion=' + (MOAT_HINTS[sym] || {}).erosion + ', severity=' + (MOAT_HINTS[sym] || {}).severity + ', earns_below_cost_of_capital=' + (MOAT_HINTS[sym] || {}).roic_below + ', returns ' + (MOAT_HINTS[sym] || {}).returns_trend + ', gross-margin ' + (MOAT_HINTS[sym] || {}).gross_margin_trend + '. The moat is ERODING by default: you must find PRIMARY-SOURCE proof of durable pricing power / rising returns to CONFIRM, else REFUTED with the moat erosion as the kill_fact.\n' : '') +
    '1. Read ' + DIR + '/results_regime/' + sym + '.json but USE ONLY: bear_thesis, sop_bear, risk_reward, catalyst_status. Read the forensic dossier ' + DIR + '/dossiers/' + sym + '.md.\n' +
    '2. WebSearch the CURRENT facts. Attack: (a) STALE-ANCHOR — is the fair value built on pre-event financials (spin/divestiture/peak quarter)? (b) NUMBER TRUTH — do the load-bearing figures (segment EBITDA, net debt, share count, preferred stack) verify against the latest primary filing? (c) THESIS WEAKNESS — is the claimed cheapness real edge, or priced/structural (melting business, governance brake, terminal multiple)? (d) HIDDEN DISQUALIFIER — litigation, covenant, dilution, regulatory action the debate missed.\n' +
    '3. Verdict: CONFIRMED (bear attacked, thesis survives) | CONFIRMED_WITH_CORRECTIONS (survives but a load-bearing number/claim needed fixing — state it) | REFUTED (a kill_fact breaks the value case). Also value_conviction_cap (int 1-5): the MAX value conviction this name deserves given what you verified.\n' +
    '4. Write (Write tool) VALID JSON to ' + DIR + '/_skeptic/' + sym + '.json = {symbol:"' + sym + '", verdict, kill_fact, corrections, value_conviction_cap, evidence:[2-4 dated primary-source cites]}. Never fabricate. Reply exactly: DONE',
    { label: 'skeptic:' + sym, phase: 'Skeptic', agentType: 'general-purpose', model: 'fable' })))
}
return 'DONE'
